In [1]:
# Import statements for this file
import bs4
import requests
import pandas as pd 
import numpy as np
from bs4 import BeautifulSoup

In [2]:
# Web scrapping initialization for PA zip code webpage 
root = "https://www.zipcodestogo.com/Pennsylvania/"
html = requests.get(root)
soup = BeautifulSoup(html.content,'html.parser')
elements = soup.select('tr a')

In [3]:
# Strip extra spaces from 'tr a' that we grabbed above 
list=[e.text.strip() for e in elements]
num=0
zip=[]
county=[]
# Loop through elements in list and append them to the correct list
for i in list:
    if (num%3==1 and num<=6571):
        zip.append(i)
    if (num%3==2 and num<=6572):
        county.append(i)
    num=num+1

In [9]:
# Create data frame of counties and zip codes scraped from website
headers = ['ZipCode', 'County']
df = pd.DataFrame(columns=headers)
point=0
num=1
repeat=[]
# Append data to df and repeat list
for i in zip:
    if (county[point] in repeat)==False:
        df.loc[num]=[i, county[point]]
        repeat.append(county[point])
        num+=1
    point+=1

In [14]:
# Create data frame of cities and zip codes scraped from website
headers = ['ZipCode', 'City']
df1 = pd.DataFrame(columns=headers)
num=0
repeat=[]
point=1
# Append data to df and repeat list
for i in elements:
    if(num%3==1 and num<=6547):
        output=i['href'].split('/')
        if (output[3] in repeat)==False:
            df1.loc[point]=[output[5], output[3]]
            repeat.append(output[3])
            point+=1
    num=num+1

In [15]:
# Save data to files
df.to_csv('County_Zip.csv', sep=',', encoding='utf-8')
df1.to_csv('City_Zip.csv', sep=',', encoding='utf-8')

In [16]:
df

   ZipCode          County
1    15001          Beaver
2    15004      Washington
3    15006       Allegheny
4    15012         Fayette
5    15062    Westmoreland
6    15310          Greene
7    15411        Somerset
8    15521         Bedford
9    15536          Fulton
10   15656       Armstrong
11   15681         Indiana
12   15711       Jefferson
13   15714         Cambria
14   15721      Clearfield
15   15821             Elk
16   15828          Forest
17   15832         Cameron
18   16001          Butler
19   16028         Clarion
20   16101        Lawrence
21   16110        Crawford
22   16113          Mercer
23   16301         Venango
24   16312          Warren
25   16333          Mckean
26   16401            Erie
27   16601           Blair
28   16611      Huntingdon
29   16677          Centre
30   16720          Potter
..     ...             ...
38   17006           Perry
39   17014         Juniata
40   17017  Northumberland
41   17019            York
42   17022       Lancaster
43   17201        Franklin
44   17301           Adams
45   17701        Lycoming
46   17731        Sullivan
47   17810           Union
48   17812          Snyder
49   17814        Columbia
50   17821         Montour
51   17901      Schuylkill
52   18001     Northampton
53   18011          Lehigh
54   18012          Carbon
55   18039           Bucks
56   18041      Montgomery
57   18056           Berks
58   18058          Monroe
59   18201         Luzerne
60   18324            Pike
61   18403      Lackawanna
62   18405           Wayne
63   18413     Susquehanna
64   18419         Wyoming
65   19008        Delaware
66   19019    Philadelphia
67   19301         Chester

[67 rows x 2 columns]

In [17]:
df1

     ZipCode              City
1      15001         Aliquippa
2      15003          Ambridge
3      15004         Atlasburg
4      15005             Baden
5      15006         Bairdford
6      15007        Bakerstown
7      15009            Beaver
8      15010      Beaver Falls
9      15012      Belle Vernon
10     15014      Brackenridge
11     15015     Bradfordwoods
12     15017       Bridgeville
13     15018       Buena Vista
14     15019            Bulger
15     15020            Bunola
16     15021      Burgettstown
17     15022         Charleroi
18     15024          Cheswick
19     15025          Clairton
20     15026           Clinton
21     15027            Conway
22     15028          Coulters
23     15030         Creighton
24     15031             Cuddy
25     15032       Curtisville
26     15033            Donora
27     15034        Dravosburg
28     15035  East Mc Keesport
29     15037         Elizabeth
30     15038            Elrama
...      ...               ...
1764   19508         Birdsboro
1765   19510           Blandon
1766   19511            Bowers
1767   19512         Boyertown
1768   19516        Centerport
1769   19518     Douglassville
1770   19519         Earlville
1771   19520          Elverson
1772   19522         Fleetwood
1773   19523        Geigertown
1774   19525     Gilbertsville
1775   19526           Hamburg
1776   19529           Kempton
1777   19530          Kutztown
1778   19533          Leesport
1779   19534     Lenhartsville
1780   19535          Limekiln
1781   19536      Lyon Station
1782   19538         Maxatawny
1783   19539         Mertztown
1784   19540           Mohnton
1785   19541        Mohrsville
1786   19542  Monocacy Station
1787   19543        Morgantown
1788   19544       Mount Aetna
1789   19545   New Berlinville
1790   19547              Oley
1791   19548        Pine Forge
1792   19549      Port Clinton
1793   19550       Rehrersburg

[1793 rows x 2 columns]